version: '3.8'

services:
  app:
    build: ./.docker/php
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db
      - minio
    command: >
      sh -c "chmod -R 777 storage bootstrap/cache &&
            chown -R www-data:www-data storage bootstrap/cache &&
            php artisan key:generate &&
            php artisan migrate --seed --force &&
            php artisan serve --host=0.0.0.0 --port=8000" #linha corrigida

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data
    entrypoint: sh -c "
        minio server /data --console-address ':9090' &
        sleep 5 &&
        mc alias set myminio http://minio:9000 admin adminpassword &&
        mc mb myminio/laravel-bucket || true"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  pgdata:
  minio-data:
