version: '3.8'

services:
  app:
    build: ./.docker/php
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=adminpassword
      - AWS_BUCKET=laravel
      - AWS_ENDPOINT=http://minio:9000
      - AWS_USE_PATH_STYLE_ENDPOINT=true
      - AWS_URL=http://127.0.0.1:9000/local
    depends_on:
      - db
      - minio
    networks:
      - laravel_network
    command: >
      sh -c "chmod -R 777 storage bootstrap/cache &&
            chown -R www-data:www-data storage bootstrap/cache &&
            sleep 10 &&
            php artisan key:generate &&
            php artisan migrate --seed --force &&
            php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - laravel_network

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    command: server /data --console-address ":9090"
    networks:
      - laravel_network

  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - laravel_network
    entrypoint: >
      /bin/sh -c "
        sleep 5 &&
        mc alias set myminio http://minio:9000 admin adminpassword &&
        mc mb myminio/laravel || true"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:
